# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "960fb5658f90de2a3abae83c740eaf93"
name = "LeakWatch Dev"
application_url = "https://leak-watch-web.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://leakwatch-api.onrender.com/v1/shopify/auth/callback",
  "https://leak-watch-web.vercel.app/v1/shopify/auth/callback"
]
